---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../../components/common
resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./etcd-defrag/ks.yaml
  - ./spegel/ks.yaml
  - ./intel-gpu-resource-driver/ks.yaml
  - ./generic-device-plugin/ks.yaml
  - ./metrics-server/ks.yaml
