---
komga:
  eventListener:
    enabled: true # if disabled will not connect to komga and won't pick up newly added entries
    metadataLibraryFilter: [] # listen to all events if empty
    metadataSeriesExcludeFilter: []
    notificationsLibraryFilter: [] # Will send notifications if any notification source is enabled. If empty will send notifications for all libraries
  metadataUpdate:
    default:
      libraryType: "MANGA" # Can be "MANGA", "NOVEL", "COMIC" or "WEBTOON". Hint to help better match book numbers
      updateModes:
        - API
        - COMIC_INFO
      aggregate: true # if enabled will search and aggregate metadata from all configured providers
      mergeTags: true # if true and aggregate is enabled will merge tags from all providers
      mergeGenres: true # if true and aggregate is enabled will merge genres from all providers
      bookCovers: true # update book thumbnails
      seriesCovers: true # update series thumbnails
      overrideExistingCovers: false # if false will upload but not select new cover if another cover already exists
      overrideComicInfo: true # Replace existing ComicInfo file. If false, only append additional data
      postProcessing:
        seriesTitle: true # update series title
        seriesTitleLanguage: "en" # series title update language. If empty chose first matching title
        fallbackToAltTitle: false # fallback to first alternative tile if series title is not found
        alternativeSeriesTitles: false # use other title types as alternative title option
        alternativeSeriesTitleLanguages: # alternative title languages
          - "en"
          - "ja"
          - "ja-ro"
        orderBooks: true # will order books using parsed volume or chapter number
        scoreTagName: "score" # adds score tag of format "score: 8" only uses integer part of rating. Can be used in search using query: tag:"score: 8" in komga
        readingDirectionValue: # override reading direction for all series. should be one of these: LEFT_TO_RIGHT, RIGHT_TO_LEFT, VERTICAL, WEBTOON
        languageValue: # set default language for series. Must use BCP 47 format e.g. "en"
        originalPublisherTagName:
        #publisherTagNames:
        #  - tagName: "English Publisher"
        #    language: "en"

database:
  file: ./database.sqlite # database file location.

metadataProviders:
  #malClientId: "${SECRET_KOMF_MAL_CLIENT_ID}" # required for mal provider. See https://myanimelist.net/forum/?topicid=1973077
  defaultProviders:
    mangaUpdates:
      priority: 10
      enabled: true
      mediaType: "MANGA" # filter used in matching. Can be NOVEL, MANGA or WEBTOON. MANGA type includes everything except novels
      authorRoles:
        - "WRITER"
      artistRoles: # roles that will be mapped to artist role
        - "PENCILLER"
        - "INKER"
        - "COLORIST"
        - "LETTERER"
        - "COVER"
    # mal:
    #   priority: 20
    #   enabled: true
    #   mediaType: "MANGA" # filter used in matching. Can be NOVEL, MANGA or WEBTOON. MANGA type includes everything except novels
    nautiljon:
      priority: 30
      enabled: false
    aniList:
      priority: 40
      enabled: true
      mediaType: "MANGA" # filter used in matching. Can be NOVEL, MANGA or WEBTOON. MANGA type includes everything except novels
      tagsScoreThreshold: 60 # tags with this score or higher will be included
      tagsSizeLimit: 15 # amount of tags that will be included
    yenPress:
      priority: 50
      enabled: false
      mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA.
    kodansha:
      priority: 60
      enabled: false
    viz:
      priority: 70
      enabled: false
    bookWalker:
      priority: 80
      enabled: true
      mediaType: "MANGA" # filter used in matching. Can be NOVEL, MANGA or WEBTOON.
    mangaDex:
      priority: 90
      enabled: true
      coverLanguages:
        - "en"
        - "ja"
    bangumi: # Chinese metadata provider. https://bgm.tv/
      priority: 100
      enabled: false
    comicVine: # https://comicvine.gamespot.com/ requires API key. Experimental provider, can mismatch issue numbers
      priority: 110
      enabled: false
    hentag:
      priority: 120
      enabled: false
    webtoons:
      priority: 130
      enabled: false
    mangaBaka:
      priority: 140
      enabled: false
      # Datasource used for metadata retrieval. DATABASE mode will only work if MangaBaka database is installed
      # API or DATABASE
      mode: API

logLevel: INFO # or env:KOMF_LOG_LEVEL
