experimental_monorepo_root = true

[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
CLUSTER = "main"
KUBECONFIG = "{{config_root}}/kubernetes/clusters/{{env.CLUSTER}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/{{env.CLUSTER}}/talosconfig"
TALOS_DIR = "{{config_root}}/talos/{{env.CLUSTER}}"
MISE_EXPERIMENTAL=1

[tools]
"python" = "3.14.3"
"pipx:makejinja" = "2.8.2"
"aqua:budimanjojo/talhelper" = "3.1.5"
"aqua:cilium/cilium-cli" = "0.19.2"
"aqua:cli/cli" = "2.87.3"
"aqua:cloudflare/cloudflared" = "2026.2.0"
"aqua:cue-lang/cue" = "0.15.4"
"aqua:FiloSottile/age" = "1.3.1"
"aqua:fluxcd/flux2" = "2.8.1"
"aqua:getsops/sops" = "3.12.1"
"aqua:go-task/task" = "3.48.0"
"aqua:helm/helm" = "4.1.1"
"aqua:helmfile/helmfile" = "1.3.2"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.33.1"
"aqua:mikefarah/yq" = "4.52.4"
"aqua:siderolabs/talos" = "1.12.4"
"aqua:yannh/kubeconform" = "0.7.0"
"aqua:google/yamlfmt" = "0.21.0"
"aqua:evilmartians/lefthook" = "2.1.2"
"aqua:mitsuhiko/minijinja" = "2.16.0"
"aqua:charmbracelet/gum" = "0.17.0"


[tasks.log]
usage = '''
arg "<lvl>"
arg "<msg>"
arg "[args]" var=#true
'''
quiet = true
run = 'gum log -t rfc3339 -s -l "${usage_lvl?}" "${usage_msg?}" ${usage_args}'


[tasks.template]
usage = '''
arg "<input>"
arg "[args]" var=#true
'''
quiet = true
run = '''
bws run --project-id 812ce0d8-ee9a-4f73-9b8d-b3970152b8ac -- \
minijinja-cli ${usage_input?} ${usage_args}
'''

