experimental_monorepo_root = true

[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
CLUSTER = "main"
KUBECONFIG = "{{config_root}}/kubernetes/clusters/{{env.CLUSTER}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/{{env.CLUSTER}}/talosconfig"
TALOS_DIR = "{{config_root}}/talos/{{env.CLUSTER}}"
MISE_EXPERIMENTAL=1

[tools]
"python" = "3.14.0"
"pipx:makejinja" = "2.8.1"
"aqua:budimanjojo/talhelper" = "3.0.39"
"aqua:cilium/cilium-cli" = "0.18.8"
"aqua:cli/cli" = "2.83.1"
"aqua:cloudflare/cloudflared" = "2025.11.1"
"aqua:cue-lang/cue" = "0.15.0"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.7.3"
"aqua:getsops/sops" = "3.11.0"
"aqua:go-task/task" = "3.45.5"
"aqua:helm/helm" = "3.19.2"
"aqua:helmfile/helmfile" = "1.1.9"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.33.1"
"aqua:mikefarah/yq" = "4.48.2"
"aqua:siderolabs/talos" = "1.11.5"
"aqua:yannh/kubeconform" = "0.7.0"
"aqua:google/yamlfmt" = "0.17.2"
"aqua:evilmartians/lefthook" = "1.13.6"
"aqua:mitsuhiko/minijinja" = "2.11.0"
"aqua:charmbracelet/gum" = "0.17.0"


[tasks.log]
usage = '''
arg "<lvl>"
arg "<msg>"
arg "[args]" var=#true
'''
quiet = true
run = 'gum log -t rfc3339 -s -l "${usage_lvl?}" "${usage_msg?}" ${usage_args}'


[tasks.template]
usage = '''
arg "<input>"
arg "[args]" var=#true
'''
quiet = true
run = '''
bws run --project-id 812ce0d8-ee9a-4f73-9b8d-b3970152b8ac -- \
minijinja-cli ${usage_input?} ${usage_args}
'''

