---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
components:
  - ../../../components/common
resources:
  - ./bazarr/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qbittorrent-vpn/ks.yaml
  - ./radarr/ks.yaml
  - ./radarr-uhd/ks.yaml
  # - ./recyclarr/ks.yaml
  - ./sonarr-tv/ks.yaml
  - ./sonarr-anm/ks.yaml
