---
# yaml-language-server: $schema=https://schemas.vzkn.eu/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}"
spec:
  sourcePVC: "${APP}"
  trigger:
    schedule: "0 * * * *"
  kopia:
    accessModes: ["${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce}"]
    cacheAccessModes: ['${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}']
    cacheCapacity: '${VOLSYNC_CACHE_CAPACITY:=5Gi}'
    cacheStorageClassName: '${VOLSYNC_CACHE_SNAPSHOTCLASS:=ceph-block}'
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=100}
      fsGroup: ${VOLSYNC_PGID:=100}
    parallelism: 2
    repository: "${APP}-volsync"
    retain:
      hourly: 24
      daily: 7
    storageClassName: "${VOLSYNC_STORAGECLASS:=ceph-block}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:=csi-ceph-blockpool}"