---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-ai-lb
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn: []
  interval: 1h
  values:
    controllers:
      local-ai:
        pod:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - "{{ .Release.Name }}"
        containers:
          app:
            image:
              repository: quay.io/go-skynet/local-ai
              tag: v3.12.1
            args: ["federated"]
            env:
              LOCALAI_CONFIG_DIR: &lbConfig /configuration
            envFrom:
              - secretRef:
                  name: local-ai-secret
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                cpu: 500m
                memory: 500Mi
    service:
      app:
        controller: local-ai
        ports:
          http:
            port: &port 8080
    route:
      app:
        hostnames:
          - "local-ai.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      backends:
        existingClaim: local-ai-backends
        globalMounts:
          - path: *lbConfig
            subPath: flux-configs
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-ai
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn: []
  interval: 1h
  values:
    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: local-ai-gpu
    controllers:
      local-ai:
        replicas: 2
        strategy: RollingUpdate
        rollingUpdate:
          surge: 0
          unavailable: 1
        pod:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - "{{ .Release.Name }}"
        containers:
          app:
            image:
              repository: quay.io/go-skynet/local-ai
              tag: v3.12.1-gpu-intel
            args: ["run", "--p2p", "--federated"]
            securityContext:
              privileged: true
            env:
              LOCALAI_MODELS_PATH: /models
              LOCALAI_CONFIG_DIR: &workerConfig /configuration
              LOCALAI_FORCE_META_BACKEND_CAPABILITY: default
              DEBUG: "true"
            envFrom:
              - secretRef:
                  name: local-ai-secret
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 800m
                memory: 8Gi
              limits:
                cpu: 8000m
                memory: 32Gi
    service:
      app:
        controller: local-ai
        ports:
          http:
            port: &port 8080
    route:
      app:
        hostnames:
          - "local-ai-worker.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      models:
        existingClaim: local-ai-models
        globalMounts:
          - path: /models
            subPath: flux-models
      backends:
        existingClaim: local-ai-backends
        globalMounts:
          - path: /backends
            subPath: flux-backends
          - path: *workerConfig
            subPath: flux-configs
      dri:
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - path: /dev/dri
