---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name neko
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: neko-secret
    template:
      data:
        NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: "{{ .NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD }}"
        NEKO_MEMBER_MULTIUSER_USER_PASSWORD: "{{ .NEKO_MEMBER_MULTIUSER_USER_PASSWORD }}"
  dataFrom:
    - extract:
        key: neko
