---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: github-webhook-token-secret
    template:
      data:
        token: "{{ .FLUX_GITHUB_WEBHOOK_TOKEN }}"
  dataFrom:
    - extract:
        key: flux
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sops-age
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: sops-age-secret
    template:
      data:
        age.agekey: "{{ .SOPS_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: AGE_KEY
