---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app etcd-defrag
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn: []
  values:
    controllers:
      etcd-defrag:
        type: cronjob
        cronjob:
          schedule: "12 9 * * 2"
          parallelism: 1
          successfulJobsHistory: 1
          failedJobsHistory: 1

        containers:
          defrag:
            image:
              repository: ghcr.io/siderolabs/talosctl
              tag: v1.12.3
            args:
              - -n
              - "192.168.1.190,192.168.1.191,192.168.1.192"
              - etcd
              - defrag

        pod:
          hostNetwork: true
          hostPID: true
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app

    persistence:
      serviceaccount:
        type: secret
        name: etcd-defrag-talos
        advancedMounts:
          etcd-defrag:
            defrag:
              - path: /var/run/secrets/talos.dev
                readOnly: true