---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../../components/common
resources:
  # - ./actual/ks.yaml
  - ./homepage/ks.yaml
  - ./monica/ks.yaml
  # - ./dawarich/ks.yaml
  # - ./paperless/ks.yaml
  # - ./syncthing/ks.yaml
  # - ./strava-statistics/ks.yaml
