---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../components/defaults
    #  - ../../../../../components/keda/nfs-scaler
    - ../../../../../components/postgres
  dependsOn:
    - name: crunchy-postgres-operator
      namespace: database

  interval: 30m
  path: ./kubernetes/apps/main/default/immich/app
  postBuild:
    substitute:
      APP: *app
      # VOLSYNC_CAPACITY: 1Gi
  patches:
    - patch: |
        - op: add
          path: /spec/patroni/dynamicConfiguration/postgresql/parameters
          value:
            shared_preload_libraries: "vchord.so"
      # search_path: '"$user", public, vectors"'
      target:
        kind: PostgresCluster
    # - patch: |
    #     - op: add
    #       path: /spec/args/-
    #       value:
    #         --default_lua_flags=allow-undeclared-keys
    #   target:
    #     kind: Dragonfly
    - patch: |
        - op: replace
          path: /spec/image
          value: ghcr.io/budimanjojo/crunchy-postgres-vectorchord:ubi9-17.6-2534
      target:
        kind: PostgresCluster
    - patch: |
        - op: add
          path: /spec/patroni/dynamicConfiguration/postgresql/pg_hba
          value:
            - hostnossl all all 10.42.0.0/16 md5
            - hostssl all all all md5
      target:
        kind: PostgresCluster
    - patch: |
        - op: add
          path: /spec/databaseInitSQL
          value:
            name: immich-database-init-sql
            key: init.sql
      target:
        kind: PostgresCluster
        # - patch: |
        #     - op: replace
        #       path: /spec/users/0
        #       value:
        #         name: immich
        #         databases: ["immich"]
        #         password:
        #           type: AlphaNumeric
        #   target:
        #     kind: PostgresCluster
        # - patch: |
        #     - op: add
        #       path: "/metadata/annotations/postgres-operator.crunchydata.com~1authorizeBackupRemoval"
        #       value: "true"
        #   target:
        #     kind: PostgresCluster
        # - patch: |
        #     - op: remove
        #       path: /spec/backups
        #   target:
        #     kind: PostgresCluster
        # - patch: |
        #     - op: remove
        #       path: /spec/dataSource
        #   target:
        #     kind: PostgresCluster
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false # no flux ks dependents
