---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
components:
  - ../../../components/common
resources:
  - ./cobalt/ks.yaml
  # - ./metabase/ks.yaml
  - ./prefect/ks.yaml
  - ./whisper/ks.yaml
  - ./n8n/ks.yaml
