# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:u1vlIaeORZY8xEbE/15Bcs32gmMeZXC0JHHC/iPDBG98PqGIITSgmylovXTrA3IRqmGyYRVQAj0Z1ak9AHsAwjhtQaG/F65bTH/IyTmSDJ6mW49OaqeAJwIafMOP8xcaEQLs8S5MmSEjlIe60McqueqqQvG5T/eJtfepRFaRWWVroGCa3QgqLvKeh2yVJGcbrwBiSsmVKJrIxYl9fXDhcwLZW1y33JP4owLan3g3C+Czxsr6m4leUSut+TIn,iv:/UBXOBGxzZUE+ltHWcp9vWGdWbbB505TjIXQNg3Pyp4=,tag:BTMm/U24e0NPD2VLoKsLPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cu2z3syq630c8w6gz7k4qfgld2kk8ydgejl2q04le0fd7yc6gs0sq3ftwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRHIwT3I4cFhKd2xRVXdY
            VCtvVWFPNkdHV2ZWWit1VjdadS9aVXMxbkF3CkxnL0tUL3ZsQUhOQ3d6MC9QamYz
            WWhXak16ZU4yZEFHZDhpN0ErbnJiK2sKLS0tIHdTWkRaUllwZGl6dVUzazJ5bFNm
            ckFKYTNJc1FqY3J4WkJPWGNoTkN3dmsKLtEZPfP8mRpDTGIsvT3r1Sp5W4hZ8RlH
            iP4GNvORaUgdSH65SjjzNvoWR0aPY2Xt5Uorkiv0iwGP12Ih9g5TuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-29T03:59:32Z"
    mac: ENC[AES256_GCM,data:xNy5B/tJDllVq7IV/RV8u9JMhzcxIBhYeNV6+0bPsJO7MiBI4xT2t9qtO51db4wnVUeujcb9JLQCo/zJaFVbL865aGYMSRV//0ucaTXWU+okir58z9U8yAg499aAA5SFZq40ZLZ4DdzQgMGrRyZi6KOJJn0SEW7B7G2uKPl7ktw=,iv:5sgtElRzSpsKHZ+DwjyKCcIs4MBvfnZZ7d5Ye1Y9h2w=,tag:XvvrO7ZXvASh7DEslGzNpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
