---
originRequest:
  http2Origin: true
  originServerName: "external.${SECRET_DOMAIN}"

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: https://envoy-external.network.svc.cluster.local
    originRequest:
      originServerName: "${SECRET_DOMAIN}"
  - hostname: "*.${SECRET_DOMAIN}"
    service: https://envoy-external.network.svc.cluster.local
  - service: http_status:404